apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: userapp
  namespace: argocd
spec:
  destination:
    namespace: userapp
    server: https://kubernetes.default.svc
  source:
    path: userapp
    repoURL: https://github.com/CodyKurtz/argocd_demo.git
    targetRevision: HEAD
